### ISSUE TITLE
无权访问此内容 请问如何获取 intune 服务

### ISSUE THREAD

**Issue by manajay** [MicrosoftDocs/IntuneDocs.zh-cn#20]
你似乎无权访问此内容。若要获取访问权限，请与所有者联系。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 48e45305-5b2e-ffc7-492b-8f02bb6a2343
* Version Independent ID: 428c2aa1-01ff-c98d-d23d-534fff973ccb
* Content: [Microsoft Intune 中的 iOS 应用预配配置文件](https://docs.microsoft.com/zh-cn/intune/app-provisioning-profile-ios)
* Content Source: [intune/app-provisioning-profile-ios.md](https://github.com/MicrosoftDocs/IntuneDocs.zh-cn/blob/live/intune/app-provisioning-profile-ios.md)
* Service: **microsoft-intune**
* Product: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by LisandroSu** [comment]
你好，@manajay

感谢你的反馈。 

您能否就此问题向我们提供更多信息？ 这是您在访问页面或按照说明操作时获得的错误消息吗？

深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
您好，@manajay

再次感谢您的评论。
很遗憾，我们仍然缺少信息，我们无法处理您的反馈。 我们目前正在关闭此GitHub问题，但我们建议您在将来提交更多反馈。

亲切的问候，
Microsoft DOCS国际团队
