### ISSUE TITLE
Not able to install management profile

### ISSUE THREAD

**Issue by zhxmarshall** [MicrosoftDocs/IntuneDocs.zh-cn#21]
When I was trying to install profile it said profile installation failed/ a connection to the server could not be established? My device is iPhone XS Max iOS 12.2. How can I solve this problem?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b00f94d8-22ab-8392-e5cb-22d1f9cc63e5
* Version Independent ID: bb6e33bd-7c8a-90ee-34a4-842ede2896df
* Content: [设置 iOS 设备对公司资源的访问](https://docs.microsoft.com/zh-cn/intune-user-help/enroll-your-device-in-intune-ios#feedback)
* Content Source: [intune-user-help/enroll-your-device-in-intune-ios.md](https://github.com/MicrosoftDocs/IntuneDocs.zh-cn/blob/live/intune-user-help/enroll-your-device-in-intune-ios.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @lenewsad
* Microsoft Alias: **lanewsad**

**Comment by CeciAc** [comment]
Hello, @zhxmarshall 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
