### ISSUE TITLE
并没有找到“全新启动”这个按钮

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/IntuneDocs.zh-cn#23]
按照文档内容执行操作，并未在Endpoint Management中找到这个全新启动按钮。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 205b487d-680c-ce11-303f-e85763ea5a42
* Version Independent ID: f7dfef7a-af4e-6d60-4e5a-ad9994a7c421
* Content: [使用 Microsoft Intune 重置 Windows 10 设备 - Azure](https://docs.microsoft.com/zh-cn/intune/remote-actions/device-fresh-start)
* Content Source: [intune/remote-actions/device-fresh-start.md](https://github.com/MicrosoftDocs/IntuneDocs.zh-cn/blob/live/intune/remote-actions/device-fresh-start.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by srvbpigh** [comment]
Hello, @goxia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@goxia
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
