### ISSUE TITLE
文档介绍内容与实际结果不同

### ISSUE THREAD

**Issue by goxia** [MicrosoftDocs/IntuneDocs.zh-cn#24]
经过测试，发起重启后客户端会收到通知，3分钟后收到一个2分钟的倒计时重启。即使在没有登录的情况下，发起重启后总长5分钟便会重启。
此外，为什么该功能可以被shutdown /a拦截。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 35307f01-fdfc-9c07-c32a-d6ceb2e75ae9
* Version Independent ID: ba1b8b62-1861-77a7-2baf-2283af641d98
* Content: [使用 Microsoft Intune 重启设备 - Azure](https://docs.microsoft.com/zh-cn/intune/remote-actions/device-restart?source=docs)
* Content Source: [intune/remote-actions/device-restart.md](https://github.com/MicrosoftDocs/IntuneDocs.zh-cn/blob/live/intune/remote-actions/device-restart.md)
* Service: **microsoft-intune**
* Sub-service: **remote-actions**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by srvbpigh** [comment]
Hello, @goxia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
你好，@goxia 

非常感谢你的参与。你的反馈与原始文档有关。  

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/IntuneDocs/issues/3419。  

非常感谢你对我们的文章作出的贡献。   

深深的祝福，  
Microsoft DOCS International Team
